version: "3"
services:
  shard00:
    image: postgres:14
    container_name: shard00
    hostname: shard00
    environment:
      POSTGRES_DB: accounts_hidden_dev
      POSTGRES_USER: accounts_hidden_dev
      POSTGRES_PASSWORD: VbVuYNiU
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - '5432:5432'
