threadCount: 4

fromProperties:
  url: jdbc:oracle:thin:@(description=(address=(host=localhost)(protocol=tcp)(port=1521))(connect_data=(service_name=ORCLPDB1)))
  user: test
  password: test
toProperties:
  url: jdbc:postgresql://localhost:5432/postgres
  user: test
  password: test
toAdds:
  cs1:
    type: cassandra
    datacenter: datacenter1
    hosts: 172.28.0.1
    port: 9042
    keyspace: store
    user: test
    password: test
    batchSize: 256
  cs2:
    type: cassandra
    datacenter: datacenter1
    hosts: 172.28.0.1
    port: 9042
    keyspace: store
    user: test
    password: test
    batchSize: 256
