threadCount: 1
initPGChunks: true
copyPGChunks: true

fromProperties:
  url: jdbc:postgresql://172.28.0.7:5432/postgres?options=-c%20enable_indexscan=off%20-c%20enable_indexonlyscan=off%20-c%20enable_bitmapscan=off
  user: test
  password: test
toProperties:
  type: cassandra
  datacenter: datacenter1
  hosts: 172.28.0.1
  port: 9042
  keyspace: store
  user: test
  password: test
  batchSize: 256
