threadCount: 10

fromProperties:
  url: jdbc:postgresql://localhost:5432/postgres?options=-c%20enable_indexscan=off%20-c%20enable_indexonlyscan=off%20-c%20enable_bitmapscan=off
  user: t
  password: t
toProperties:
  url: jdbc:postgresql://localhost:5432/postgres
  user: test
  password: test
